### ISSUE TITLE
Difficult endgame, but winning

### ISSUE THREAD

**Issue by tissatussa** [bagaturchess/Bagatur#14]
This position might be interesting for endgame testing : 8/7p/8/5n1K/4n1P1/k7/5P2/8 b - - 0 1
I checked the online TBs at https://syzygy-tables.info :

![Nf6+ is draw](https://user-images.githubusercontent.com/1109281/144038885-e6af69c6-0abe-4cbc-82a8-a4dfbb56f991.png)

Black is able to win this endgame, but it's difficult (for a human).
In the actual game Black played Nf6+ and made a draw.

**Comment by meade88** [comment]
Hi,

I'd also include this endgame that came up recently in TCEC where Bagatur 2.2e was unfortunately not able to find the winning continuation against Vajolet. 8/5k2/4R3/5P1K/7P/5P2/8/6r1 b - - 0 96
<img width="451" alt="Bildschirmfoto 2021-11-30 um 13 11 27" src="https://user-images.githubusercontent.com/95288414/144045084-a12dc283-298c-423c-a602-527c443b7bc2.png">

Also I noticed a dramatic decrease of the NPS in those endgame positions for Bagatur in TCEC? Is that due to TBs?

**Comment by bagaturchess** [comment]
Hi All,

Thanks for this positions!

I will have a look as soon as possible.

Yes, TBs create dramatic decrease, sometimes even around 10 times.

Best regards,
Krasimir

**Comment by bagaturchess** [comment]
Syzygy EGTBs are implemented and there is an UCI option to point to the files.
