### ISSUE TITLE
Huge memory use

### ISSUE THREAD

**Issue by SzotsGabor** [bagaturchess/Bagatur#20]
Hi Krasimir,

Under Arena, I can see that allocated memory is well above 2 GB although I use 256 MB hash tables. I can see there is a parameter vm.heapsize.preferred which is set to 4096 MB. I changed that to 1024 MB but the memory usage is still greater than that of version 3.3 which  I used last time.

What is the reason and how important this parameter is?

Gabor Szots
CCRL testing group

**Comment by bagaturchess** [comment]
Hi Gabor,
Thanks for reaching out and sorry for the late reply!
You could set vm.heapsize.preferred in the ini file of the corresponding exe runner as you have done.If it is more than you would like, I think it can be decreased to 512MB. Also there is a UCI option, which defines what percent Transposition Table should use from its max available memory.If you run matches on long time controls, than the memory is quite important, because it affects the search if the Transposition Table is not big enough. The logic, which I use when run tournaments is, if the TT is filled at 100% after the first 1 or 2 moves thinking, than it is good.
Feel free to contact me in case of further questions.
Best regards,Krasimir
    On Friday, February 10, 2023 at 01:04:56 PM GMT+2, Gabor Szots ***@***.***> wrote:  
 
 


Hi Krasimir,

Under Arena, I can see that allocated memory is well above 2 GB although I use 256 MB hash tables. I can see there is a parameter vm.heapsize.preferred which is set to 4096 MB. I changed that to 1024 MB but the memory usage is still greater than that of version 3.3 which I used last time.

What is the reason and how important this parameter is?

Gabor Szots
CCRL testing group

**Comment by bagaturchess** [comment]
The java could be found at https://www.java.com/download/ie_manual.jsp
