### ISSUE TITLE
Which java version

### ISSUE THREAD

**Issue by SzotsGabor** [bagaturchess/Bagatur#6]
When I used Java 8 I had no problem using Bagatur via Bagatur_64_1_core.exe. Yesterday I deleted Java 8 and installed JDK 14 and now Bagatur does not find Java VM although I have the path environment variable correctly modified.
I am no programmer and don't know what the problem might be. Shall I reinstall Java 8? I would do that reluctantly because some engines (e.g. chess22k) don't work with it and the path would point to the wrong java for them.
What do you suggest?

Regards,
Gabor Szots
CCRL testing group

**Comment by bagaturchess** [comment]
Hi Gabor Szots,
what JDK 14 are you using, 32 bits or 64 bits ?
Best Regards,Krasimir    On Wednesday, April 29, 2020, 10:06:28 AM GMT+3, SzotsGabor <notifications@github.com> wrote:  
 
 


When I used Java 8 I had no problem using Bagatur via Bagatur_64_1_core.exe. Yesterday I deleted Java 8 and installed JDK 14 and now Bagatur does not find Java VM although I have the path environment variable correctly modified.
I am no programmer and don't know what the problem might be. Shall I reinstall Java 8? I would do that reluctantly because some engines (e.g. chess22k) don't work with it and the path would point to the wrong java for them.
What do you suggest?

Regards,
Gabor Szots
CCRL testing group

**Comment by SzotsGabor** [comment]
It is 64-bit.

**Comment by bagaturchess** [comment]
Hi Gabor Szots,

I assume that we are talking about Windows operating system ...

Could you please try to edit the Bagatur_64_1_core.ini file?

It is about the line ";vm.location=C:\jdk1.6.0_07\jre\bin\client\jvm.dll".
First remove the ";" symbol and then edit the vm.location variable to point to the right jvm.dll file on your file system. It should be somewhere inside the JDK 14 installation folder like \jre\bin\client\jvm.dll.
I am looking forward for your feedback ...

Best Regards,
Krasimir

**Comment by SzotsGabor** [comment]
Hi Krasimir,

I have found the file at c:\Program Files\Java\jdk-14.0.1\bin\server\jvm.dll and after editing the ini Bagatur works again. :)
 I will now remember to edit that file again if I ever upgrade my java.
Thanks for the quick help.

Keep up the good work.

Best regards,
Gabor

**Comment by bagaturchess** [comment]
Hi Gabor,

I am also happy to hear that it works again. :-)

Best Regards,
Krasimir

**Comment by bagaturchess** [comment]
Hi Gabor,

I am also happy to hear that it works again. :-)

Best Regards,
Krasimir
